#
# Makefile for the linux kernel.
#

ifdef CONFIG_FUNCTION_TRACER
# Do not profile debug and lowlevel utilities
CFLAGS_REMOVE_tsc.o = -pg
CFLAGS_REMOVE_paravirt-spinlocks.o = -pg
CFLAGS_REMOVE_pvclock.o = -pg
CFLAGS_REMOVE_kvmclock.o = -pg
CFLAGS_REMOVE_ftrace.o = -pg
CFLAGS_REMOVE_early_printk.o = -pg
endif

obj-$(CONFIG_ASMP) 		+= autosmp.o
obj-$(CONFIG_ALUCARD_HOTPLUG) 		+= alucard_hotplug.o
obj-$(CONFIG_INTELLI_PLUG) += intelli_plug.o
